version: '3.8'

services:
  cosmoweb:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    networks:
      - cosmoweb-network

networks:
  cosmoweb-network:
    driver: bridge 